### ISSUE TITLE
Tests don't build with check 0.9.9

### ISSUE THREAD

**Issue by tuxmaster** [signalapp/libsignal-protocol-c#102]
Tested with  2.3.1
It looks like, cmake don't check the version of check.
0.9.9 will fails with:
```
CMakeFiles/test_device_consistency.dir/test_device_consistency.c.o: In function `generate_code':
/builddir/build/BUILD/libsignal-protocol-c-2.3.1/tests/test_device_consistency.c:208: undefined reference to `ck_assert_ptr_ne'
/builddir/build/BUILD/libsignal-protocol-c-2.3.1/tests/test_device_consistency.c:219: undefined reference to `ck_assert_ptr_ne'
CMakeFiles/test_device_consistency.dir/test_device_consistency.c.o: In function `test_device_consistency':
/builddir/build/BUILD/libsignal-protocol-c-2.3.1/tests/test_device_consistency.c:55: undefined reference to `ck_assert_ptr_ne'
/builddir/build/BUILD/libsignal-protocol-c-2.3.1/tests/test_device_consistency.c:68: undefined reference to `ck_assert_ptr_ne'
/builddir/build/BUILD/libsignal-protocol-c-2.3.1/tests/test_device_consistency.c:81: undefined reference to `ck_assert_ptr_ne'
/builddir/build/BUILD/libsignal-protocol-c-2.3.1/tests/test_group_cipher.c:565: undefined reference to `ck_assert_ptr_eq'
CMakeFiles/test_group_cipher.dir/test_group_cipher.c.o: In function `test_basic_ratchet':
/builddir/build/BUILD/libsignal-protocol-c-2.3.1/tests/test_group_cipher.c:288: undefined reference to `ck_assert_ptr_eq'
CMakeFiles/test_group_cipher.dir/test_group_cipher.c.o: In function `test_message_key_limit':
/builddir/build/BUILD/libsignal-protocol-c-2.3.1/tests/test_group_cipher.c:708: undefined reference to `ck_assert_ptr_ne'
/builddir/build/BUILD/libsignal-protocol-c-2.3.1/tests/test_group_cipher.c:714: undefined reference to `ck_assert_ptr_ne'
collect2: error: ld returned 1 exit status
make[2]: *** [tests/test_group_cipher] Error 1

```

**Comment by tuxmaster** [comment]
check 0.11.0 will do its job.
